// Auto-generated by deploy-ui.py — do not edit manually
const FIREBASE_CONFIG = {
  apiKey:     "AIzaSyDOFZYJrvzjdgFEouAqMespG6hl1aPi5kE",
  authDomain: "debatrium-fa490.firebaseapp.com",
  projectId:  "debatrium-fa490",
};
const API_URL = "https://yfp980t3ji.execute-api.us-east-1.amazonaws.com/prod";
