"""
deploy-ui.py — Build and deploy the Debatrium UI to S3 static hosting.

Run from milestone-4/:
  python infra/deploy-ui.py

What it does:
  1. Reads Firebase + API Gateway config from debate_config.json
  2. Generates ui/firebase-config.js with the real credentials
  3. Creates an S3 bucket for static website hosting (public read)
  4. Uploads all files from ui/
  5. Prints the public URL

Prerequisites (one-time in Firebase console):
  - Enable Firestore: Firebase console → Build → Firestore Database → Create database
  - Set security rules (printed below when script runs)
"""

import boto3
import json
import os
import sys
import mimetypes
from botocore.exceptions import ClientError

CONFIG_FILE = os.path.join(os.path.dirname(__file__), "..", "debate_config.json")
UI_DIR      = os.path.join(os.path.dirname(__file__), "..", "ui")

with open(os.path.abspath(CONFIG_FILE)) as f:
    cfg = json.load(f)

for section in ("firebase", "api_gateway"):
    if section not in cfg:
        print(f"ERROR: No '{section}' section in debate_config.json.")
        print(f"       Run python infra/setup-firebase.py and python infra/create-api-auth.py first.")
        sys.exit(1)

REGION      = cfg["region"]
ACCOUNT_ID  = cfg["account_id"]
PROJECT_ID  = cfg["firebase"]["project_id"]
WEB_API_KEY = cfg["firebase"]["web_api_key"]
API_URL     = cfg["api_gateway"]["url"].rstrip("/")
BUCKET_NAME = f"debate-ui-{ACCOUNT_ID[-6:]}"

s3 = boto3.client("s3", region_name=REGION)


def log(msg):     print(f"  -> {msg}")
def ok(msg):      print(f"  OK {msg}")
def skip(msg):    print(f"  -- {msg}")
def section(msg): print(f"\n{'='*60}\n  {msg}\n{'='*60}")


# ─────────────────────────────────────────────────────────────
# STEP 1 — GENERATE firebase-config.js
# ─────────────────────────────────────────────────────────────
def generate_config():
    section("Step 1 — Generating firebase-config.js")

    config_js = f"""// Auto-generated by deploy-ui.py — do not edit manually
const FIREBASE_CONFIG = {{
  apiKey:     "{WEB_API_KEY}",
  authDomain: "{PROJECT_ID}.firebaseapp.com",
  projectId:  "{PROJECT_ID}",
}};
const API_URL = "{API_URL}";
"""
    out_path = os.path.join(os.path.abspath(UI_DIR), "firebase-config.js")
    with open(out_path, "w") as f:
        f.write(config_js)
    ok(f"Written: ui/firebase-config.js")
    ok(f"  Firebase project : {PROJECT_ID}")
    ok(f"  API URL          : {API_URL}")


# ─────────────────────────────────────────────────────────────
# STEP 2 — CREATE S3 BUCKET
# ─────────────────────────────────────────────────────────────
def create_bucket():
    section("Step 2 — S3 bucket")

    try:
        s3.head_bucket(Bucket=BUCKET_NAME)
        skip(f"Bucket already exists: {BUCKET_NAME}")
        return
    except ClientError as e:
        if e.response["Error"]["Code"] != "404":
            raise

    log(f"Creating bucket: {BUCKET_NAME}")
    if REGION == "us-east-1":
        s3.create_bucket(Bucket=BUCKET_NAME)
    else:
        s3.create_bucket(
            Bucket=BUCKET_NAME,
            CreateBucketConfiguration={"LocationConstraint": REGION},
        )
    ok(f"Bucket created: {BUCKET_NAME}")


# ─────────────────────────────────────────────────────────────
# STEP 3 — CONFIGURE PUBLIC STATIC WEBSITE HOSTING
# ─────────────────────────────────────────────────────────────
def configure_hosting():
    section("Step 3 — Static website hosting")

    log("Disabling block public access...")
    s3.put_public_access_block(
        Bucket=BUCKET_NAME,
        PublicAccessBlockConfiguration={
            "BlockPublicAcls":       False,
            "IgnorePublicAcls":      False,
            "BlockPublicPolicy":     False,
            "RestrictPublicBuckets": False,
        },
    )

    log("Setting bucket policy (public read)...")
    policy = json.dumps({
        "Version": "2012-10-17",
        "Statement": [{
            "Sid":       "PublicReadGetObject",
            "Effect":    "Allow",
            "Principal": "*",
            "Action":    "s3:GetObject",
            "Resource":  f"arn:aws:s3:::{BUCKET_NAME}/*",
        }],
    })
    s3.put_bucket_policy(Bucket=BUCKET_NAME, Policy=policy)

    log("Enabling static website hosting...")
    s3.put_bucket_website(
        Bucket=BUCKET_NAME,
        WebsiteConfiguration={
            "IndexDocument": {"Suffix": "index.html"},
            "ErrorDocument": {"Key":    "index.html"},
        },
    )
    ok("Static hosting enabled")


# ─────────────────────────────────────────────────────────────
# STEP 4 — UPLOAD FILES
# ─────────────────────────────────────────────────────────────
def upload_files():
    section("Step 4 — Uploading UI files")

    ui_dir   = os.path.abspath(UI_DIR)
    uploaded = 0

    for fname in sorted(os.listdir(ui_dir)):
        fpath = os.path.join(ui_dir, fname)
        if not os.path.isfile(fpath):
            continue

        content_type = mimetypes.guess_type(fname)[0] or "application/octet-stream"
        log(f"Uploading {fname} ({content_type})")

        s3.upload_file(
            fpath, BUCKET_NAME, fname,
            ExtraArgs={"ContentType": content_type},
        )
        uploaded += 1

    ok(f"Uploaded {uploaded} file(s)")


# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────
def main():
    print("\n" + "=" * 60)
    print("  DEBATE SYSTEM — UI Deploy")
    print("=" * 60)
    print(f"\n  Region  : {REGION}")
    print(f"  Bucket  : {BUCKET_NAME}")
    print(f"  Firebase: {PROJECT_ID}")
    print()

    generate_config()
    create_bucket()
    configure_hosting()
    upload_files()

    url = f"http://{BUCKET_NAME}.s3-website-{REGION}.amazonaws.com"

    cfg["ui"] = {"bucket": BUCKET_NAME, "url": url}
    with open(os.path.abspath(CONFIG_FILE), "w") as f:
        json.dump(cfg, f, indent=2)

    print("\n" + "=" * 60)
    print("  DONE")
    print("=" * 60)
    print(f"\n  UI URL : {url}")
    print()
    print("  ⚠️  One-time Firestore setup required (if not done yet):")
    print("  1. Firebase console → Build → Firestore Database → Create database")
    print("     (choose production mode, pick us-east1 region)")
    print()
    print("  2. Rules tab → Replace with:")
    print()
    print("""     rules_version = '2';
     service cloud.firestore {
       match /databases/{database}/documents {
         match /debates/{debateId} {
           allow read, update: if request.auth != null
             && request.auth.uid == resource.data.userId;
           allow create: if request.auth != null
             && request.auth.uid == request.resource.data.userId;
         }
       }
     }""")
    print()
    print("  3. Click Publish")
    print()
    print(f"  Then open: {url}")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()
